package com.mobdeve.s16.group4mco

// Data class representing a habit entity in the app
data class Habit(
    val id: Int = 0,                 // Unique ID of the habit (autogenerated by DB)
    val name: String,                // Name of the habit
    val category: String,            // Category of the habit (e.g., Health, Study, Lifestyle)
    val description: String,         // Optional description of the habit
    val frequency: String,           // Frequency of the habit (e.g., Daily, 3x/week)
    val reminderTime: String         // Reminder time in HH:mm format
)
